name: Release Build

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Build (Release)
        run: cargo build --release

      - name: Create .app bundle
        run: |
          mkdir -p Redock.app/Contents/{MacOS,Resources}
          cp target/release/redock Redock.app/Contents/MacOS/
          cp assets/redock.icns Redock.app/Contents/Resources/
          
          cat > Redock.app/Contents/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleName</key>
            <string>redock</string>
            <key>CFBundleIconFile</key>
            <string>redock.icns</string>
            <key>CFBundleExecutable</key>
            <string>redock</string>
          </dict>
          </plist>
          EOF

      - name: Create archive
        run: tar -czvf Redock-${{ github.ref_name }}.tar.gz Redock.app

      - uses: actions/upload-artifact@v4
        with:
          name: Redock-${{ github.ref_name }}
          path: Redock-${{ github.ref_name }}.tar.gz
